// AUTO-GENERATED FILE - Do not edit manually
// Generated by: node scripts/buildEvents.js
// This file registers ALL hooks for testing purposes

import nodemodCore from '@nodemod/core';

// Total hooks: 410

nodemod.on('dllGameInit', () => {
  console.log('[dllGameInit]');
});

nodemod.on('dllSpawn', (pent) => {
  console.log('[dllSpawn]', 'pent:', pent);
});

nodemod.on('dllThink', (pent) => {
  console.log('[dllThink]', 'pent:', pent);
});

nodemod.on('dllUse', (pentUsed, pentOther) => {
  console.log('[dllUse]', 'pentUsed:', pentUsed, 'pentOther:', pentOther);
});

nodemod.on('dllTouch', (pentTouched, pentOther) => {
  console.log('[dllTouch]', 'pentTouched:', pentTouched, 'pentOther:', pentOther);
});

nodemod.on('dllBlocked', (pentBlocked, pentOther) => {
  console.log('[dllBlocked]', 'pentBlocked:', pentBlocked, 'pentOther:', pentOther);
});

nodemod.on('dllKeyValue', (pentKeyvalue, pkvd) => {
  console.log('[dllKeyValue]', 'pentKeyvalue:', pentKeyvalue, 'pkvd:', pkvd);
});

nodemod.on('dllSave', (pent, pSaveData) => {
  console.log('[dllSave]', 'pent:', pent, 'pSaveData:', pSaveData);
});

nodemod.on('dllRestore', (pent, pSaveData, globalEntity) => {
  console.log('[dllRestore]', 'pent:', pent, 'pSaveData:', pSaveData, 'globalEntity:', globalEntity);
});

nodemod.on('dllSetAbsBox', (pent) => {
  console.log('[dllSetAbsBox]', 'pent:', pent);
});

nodemod.on('dllSaveWriteFields', (value0, value1, value2, value3, value4) => {
  console.log('[dllSaveWriteFields]', 'value0:', value0, 'value1:', value1, 'value2:', value2, 'value3:', value3, 'value4:', value4);
});

nodemod.on('dllSaveReadFields', (value0, value1, value2, value3, value4) => {
  console.log('[dllSaveReadFields]', 'value0:', value0, 'value1:', value1, 'value2:', value2, 'value3:', value3, 'value4:', value4);
});

nodemod.on('dllSaveGlobalState', (value0) => {
  console.log('[dllSaveGlobalState]', 'value0:', value0);
});

nodemod.on('dllRestoreGlobalState', (value0) => {
  console.log('[dllRestoreGlobalState]', 'value0:', value0);
});

nodemod.on('dllResetGlobalState', () => {
  console.log('[dllResetGlobalState]');
});

nodemod.on('dllClientConnect', (pEntity, pszName, pszAddress, szRejectReason) => {
  console.log('[dllClientConnect]', 'pEntity:', pEntity, 'pszName:', pszName, 'pszAddress:', pszAddress, 'szRejectReason:', szRejectReason);
});

nodemod.on('dllClientDisconnect', (pEntity) => {
  console.log('[dllClientDisconnect]', 'pEntity:', pEntity);
});

nodemod.on('dllClientKill', (pEntity) => {
  console.log('[dllClientKill]', 'pEntity:', pEntity);
});

nodemod.on('dllClientPutInServer', (pEntity) => {
  console.log('[dllClientPutInServer]', 'pEntity:', pEntity);
});

nodemod.on('dllClientCommand', (client, commandText) => {
  console.log('[dllClientCommand]', 'client:', client, 'commandText:', commandText);
});

nodemod.on('dllClientUserInfoChanged', (pEntity, infobuffer) => {
  console.log('[dllClientUserInfoChanged]', 'pEntity:', pEntity, 'infobuffer:', infobuffer);
});

nodemod.on('dllServerActivate', (pEdictList, edictCount, clientMax) => {
  console.log('[dllServerActivate]', 'pEdictList:', pEdictList, 'edictCount:', edictCount, 'clientMax:', clientMax);
});

nodemod.on('dllServerDeactivate', () => {
  console.log('[dllServerDeactivate]');
});

nodemod.on('dllPlayerPreThink', (pEntity) => {
  console.log('[dllPlayerPreThink]', 'pEntity:', pEntity);
});

nodemod.on('dllPlayerPostThink', (pEntity) => {
  console.log('[dllPlayerPostThink]', 'pEntity:', pEntity);
});

nodemod.on('dllStartFrame', () => {
  console.log('[dllStartFrame]');
});

nodemod.on('dllParmsNewLevel', () => {
  console.log('[dllParmsNewLevel]');
});

nodemod.on('dllParmsChangeLevel', () => {
  console.log('[dllParmsChangeLevel]');
});

nodemod.on('dllGetGameDescription', () => {
  console.log('[dllGetGameDescription]');
});

nodemod.on('dllPlayerCustomization', (pEntity, pCustom) => {
  console.log('[dllPlayerCustomization]', 'pEntity:', pEntity, 'pCustom:', pCustom);
});

nodemod.on('dllSpectatorConnect', (pEntity) => {
  console.log('[dllSpectatorConnect]', 'pEntity:', pEntity);
});

nodemod.on('dllSpectatorDisconnect', (pEntity) => {
  console.log('[dllSpectatorDisconnect]', 'pEntity:', pEntity);
});

nodemod.on('dllSpectatorThink', (pEntity) => {
  console.log('[dllSpectatorThink]', 'pEntity:', pEntity);
});

nodemod.on('dllSysError', (error_string) => {
  console.log('[dllSysError]', 'error_string:', error_string);
});

nodemod.on('dllPMMove', (ppmove, server) => {
  console.log('[dllPMMove]', 'ppmove:', ppmove, 'server:', server);
});

nodemod.on('dllPMInit', (ppmove) => {
  console.log('[dllPMInit]', 'ppmove:', ppmove);
});

nodemod.on('dllPMFindTextureType', (name) => {
  console.log('[dllPMFindTextureType]', 'name:', name);
});

nodemod.on('dllSetupVisibility', (pViewEntity, pClient, pvs, pas) => {
  console.log('[dllSetupVisibility]', 'pViewEntity:', pViewEntity, 'pClient:', pClient, 'pvs:', pvs, 'pas:', pas);
});

nodemod.on('dllUpdateClientData', (ent, sendweapons, cd) => {
  console.log('[dllUpdateClientData]', 'ent:', ent, 'sendweapons:', sendweapons, 'cd:', cd);
});

nodemod.on('dllAddToFullPack', (state, e, ent, host, hostflags, player, pSet) => {
  console.log('[dllAddToFullPack]', 'state:', state, 'e:', e, 'ent:', ent, 'host:', host, 'hostflags:', hostflags, 'player:', player, 'pSet:', pSet);
});

nodemod.on('dllCreateBaseline', (player, eindex, baseline, entity, playermodelindex, player_mins, player_maxs) => {
  console.log('[dllCreateBaseline]', 'player:', player, 'eindex:', eindex, 'baseline:', baseline, 'entity:', entity, 'playermodelindex:', playermodelindex, 'player_mins:', player_mins, 'player_maxs:', player_maxs);
});

nodemod.on('dllRegisterEncoders', () => {
  console.log('[dllRegisterEncoders]');
});

nodemod.on('dllGetWeaponData', (player, info) => {
  console.log('[dllGetWeaponData]', 'player:', player, 'info:', info);
});

nodemod.on('dllCmdStart', (player, cmd, random_seed) => {
  console.log('[dllCmdStart]', 'player:', player, 'cmd:', cmd, 'random_seed:', random_seed);
});

nodemod.on('dllCmdEnd', (player) => {
  console.log('[dllCmdEnd]', 'player:', player);
});

nodemod.on('dllConnectionlessPacket', (net_from, args, response_buffer, response_buffer_size) => {
  console.log('[dllConnectionlessPacket]', 'net_from:', net_from, 'args:', args, 'response_buffer:', response_buffer, 'response_buffer_size:', response_buffer_size);
});

nodemod.on('dllGetHullBounds', (hullnumber, mins, maxs) => {
  console.log('[dllGetHullBounds]', 'hullnumber:', hullnumber, 'mins:', mins, 'maxs:', maxs);
});

nodemod.on('dllCreateInstancedBaselines', () => {
  console.log('[dllCreateInstancedBaselines]');
});

nodemod.on('dllInconsistentFile', (player, filename, disconnect_message) => {
  console.log('[dllInconsistentFile]', 'player:', player, 'filename:', filename, 'disconnect_message:', disconnect_message);
});

nodemod.on('dllAllowLagCompensation', () => {
  console.log('[dllAllowLagCompensation]');
});

nodemod.on('postDllGameInit', () => {
  console.log('[postDllGameInit]');
});

nodemod.on('postDllSpawn', (pent) => {
  console.log('[postDllSpawn]', 'pent:', pent);
});

nodemod.on('postDllThink', (pent) => {
  console.log('[postDllThink]', 'pent:', pent);
});

nodemod.on('postDllUse', (pentUsed, pentOther) => {
  console.log('[postDllUse]', 'pentUsed:', pentUsed, 'pentOther:', pentOther);
});

nodemod.on('postDllTouch', (pentTouched, pentOther) => {
  console.log('[postDllTouch]', 'pentTouched:', pentTouched, 'pentOther:', pentOther);
});

nodemod.on('postDllBlocked', (pentBlocked, pentOther) => {
  console.log('[postDllBlocked]', 'pentBlocked:', pentBlocked, 'pentOther:', pentOther);
});

nodemod.on('postDllKeyValue', (pentKeyvalue, pkvd) => {
  console.log('[postDllKeyValue]', 'pentKeyvalue:', pentKeyvalue, 'pkvd:', pkvd);
});

nodemod.on('postDllSave', (pent, pSaveData) => {
  console.log('[postDllSave]', 'pent:', pent, 'pSaveData:', pSaveData);
});

nodemod.on('postDllRestore', (pent, pSaveData, globalEntity) => {
  console.log('[postDllRestore]', 'pent:', pent, 'pSaveData:', pSaveData, 'globalEntity:', globalEntity);
});

nodemod.on('postDllSetAbsBox', (pent) => {
  console.log('[postDllSetAbsBox]', 'pent:', pent);
});

nodemod.on('postDllSaveWriteFields', (value0, value1, value2, value3, value4) => {
  console.log('[postDllSaveWriteFields]', 'value0:', value0, 'value1:', value1, 'value2:', value2, 'value3:', value3, 'value4:', value4);
});

nodemod.on('postDllSaveReadFields', (value0, value1, value2, value3, value4) => {
  console.log('[postDllSaveReadFields]', 'value0:', value0, 'value1:', value1, 'value2:', value2, 'value3:', value3, 'value4:', value4);
});

nodemod.on('postDllSaveGlobalState', (value0) => {
  console.log('[postDllSaveGlobalState]', 'value0:', value0);
});

nodemod.on('postDllRestoreGlobalState', (value0) => {
  console.log('[postDllRestoreGlobalState]', 'value0:', value0);
});

nodemod.on('postDllResetGlobalState', () => {
  console.log('[postDllResetGlobalState]');
});

nodemod.on('postDllClientConnect', (pEntity, pszName, pszAddress, szRejectReason) => {
  console.log('[postDllClientConnect]', 'pEntity:', pEntity, 'pszName:', pszName, 'pszAddress:', pszAddress, 'szRejectReason:', szRejectReason);
});

nodemod.on('postDllClientDisconnect', (pEntity) => {
  console.log('[postDllClientDisconnect]', 'pEntity:', pEntity);
});

nodemod.on('postDllClientKill', (pEntity) => {
  console.log('[postDllClientKill]', 'pEntity:', pEntity);
});

nodemod.on('postDllClientPutInServer', (pEntity) => {
  console.log('[postDllClientPutInServer]', 'pEntity:', pEntity);
});

nodemod.on('postDllClientCommand', (client, commandText) => {
  console.log('[postDllClientCommand]', 'client:', client, 'commandText:', commandText);
});

nodemod.on('postDllClientUserInfoChanged', (pEntity, infobuffer) => {
  console.log('[postDllClientUserInfoChanged]', 'pEntity:', pEntity, 'infobuffer:', infobuffer);
});

nodemod.on('postDllServerActivate', (pEdictList, edictCount, clientMax) => {
  console.log('[postDllServerActivate]', 'pEdictList:', pEdictList, 'edictCount:', edictCount, 'clientMax:', clientMax);
});

nodemod.on('postDllServerDeactivate', () => {
  console.log('[postDllServerDeactivate]');
});

nodemod.on('postDllPlayerPreThink', (pEntity) => {
  console.log('[postDllPlayerPreThink]', 'pEntity:', pEntity);
});

nodemod.on('postDllPlayerPostThink', (pEntity) => {
  console.log('[postDllPlayerPostThink]', 'pEntity:', pEntity);
});

nodemod.on('postDllStartFrame', () => {
  console.log('[postDllStartFrame]');
});

nodemod.on('postDllParmsNewLevel', () => {
  console.log('[postDllParmsNewLevel]');
});

nodemod.on('postDllParmsChangeLevel', () => {
  console.log('[postDllParmsChangeLevel]');
});

nodemod.on('postDllGetGameDescription', () => {
  console.log('[postDllGetGameDescription]');
});

nodemod.on('postDllPlayerCustomization', (pEntity, pCustom) => {
  console.log('[postDllPlayerCustomization]', 'pEntity:', pEntity, 'pCustom:', pCustom);
});

nodemod.on('postDllSpectatorConnect', (pEntity) => {
  console.log('[postDllSpectatorConnect]', 'pEntity:', pEntity);
});

nodemod.on('postDllSpectatorDisconnect', (pEntity) => {
  console.log('[postDllSpectatorDisconnect]', 'pEntity:', pEntity);
});

nodemod.on('postDllSpectatorThink', (pEntity) => {
  console.log('[postDllSpectatorThink]', 'pEntity:', pEntity);
});

nodemod.on('postDllSysError', (error_string) => {
  console.log('[postDllSysError]', 'error_string:', error_string);
});

nodemod.on('postDllPMMove', (ppmove, server) => {
  console.log('[postDllPMMove]', 'ppmove:', ppmove, 'server:', server);
});

nodemod.on('postDllPMInit', (ppmove) => {
  console.log('[postDllPMInit]', 'ppmove:', ppmove);
});

nodemod.on('postDllPMFindTextureType', (name) => {
  console.log('[postDllPMFindTextureType]', 'name:', name);
});

nodemod.on('postDllSetupVisibility', (pViewEntity, pClient, pvs, pas) => {
  console.log('[postDllSetupVisibility]', 'pViewEntity:', pViewEntity, 'pClient:', pClient, 'pvs:', pvs, 'pas:', pas);
});

nodemod.on('postDllUpdateClientData', (ent, sendweapons, cd) => {
  console.log('[postDllUpdateClientData]', 'ent:', ent, 'sendweapons:', sendweapons, 'cd:', cd);
});

nodemod.on('postDllAddToFullPack', (state, e, ent, host, hostflags, player, pSet) => {
  console.log('[postDllAddToFullPack]', 'state:', state, 'e:', e, 'ent:', ent, 'host:', host, 'hostflags:', hostflags, 'player:', player, 'pSet:', pSet);
});

nodemod.on('postDllCreateBaseline', (player, eindex, baseline, entity, playermodelindex, player_mins, player_maxs) => {
  console.log('[postDllCreateBaseline]', 'player:', player, 'eindex:', eindex, 'baseline:', baseline, 'entity:', entity, 'playermodelindex:', playermodelindex, 'player_mins:', player_mins, 'player_maxs:', player_maxs);
});

nodemod.on('postDllRegisterEncoders', () => {
  console.log('[postDllRegisterEncoders]');
});

nodemod.on('postDllGetWeaponData', (player, info) => {
  console.log('[postDllGetWeaponData]', 'player:', player, 'info:', info);
});

nodemod.on('postDllCmdStart', (player, cmd, random_seed) => {
  console.log('[postDllCmdStart]', 'player:', player, 'cmd:', cmd, 'random_seed:', random_seed);
});

nodemod.on('postDllCmdEnd', (player) => {
  console.log('[postDllCmdEnd]', 'player:', player);
});

nodemod.on('postDllConnectionlessPacket', (net_from, args, response_buffer, response_buffer_size) => {
  console.log('[postDllConnectionlessPacket]', 'net_from:', net_from, 'args:', args, 'response_buffer:', response_buffer, 'response_buffer_size:', response_buffer_size);
});

nodemod.on('postDllGetHullBounds', (hullnumber, mins, maxs) => {
  console.log('[postDllGetHullBounds]', 'hullnumber:', hullnumber, 'mins:', mins, 'maxs:', maxs);
});

nodemod.on('postDllCreateInstancedBaselines', () => {
  console.log('[postDllCreateInstancedBaselines]');
});

nodemod.on('postDllInconsistentFile', (player, filename, disconnect_message) => {
  console.log('[postDllInconsistentFile]', 'player:', player, 'filename:', filename, 'disconnect_message:', disconnect_message);
});

nodemod.on('postDllAllowLagCompensation', () => {
  console.log('[postDllAllowLagCompensation]');
});

nodemod.on('engPrecacheModel', (s) => {
  console.log('[engPrecacheModel]', 's:', s);
});

nodemod.on('engPrecacheSound', (s) => {
  console.log('[engPrecacheSound]', 's:', s);
});

nodemod.on('engSetModel', (e, m) => {
  console.log('[engSetModel]', 'e:', e, 'm:', m);
});

nodemod.on('engModelIndex', (m) => {
  console.log('[engModelIndex]', 'm:', m);
});

nodemod.on('engModelFrames', (modelIndex) => {
  console.log('[engModelFrames]', 'modelIndex:', modelIndex);
});

nodemod.on('engSetSize', (e, rgflMin, rgflMax) => {
  console.log('[engSetSize]', 'e:', e, 'rgflMin:', rgflMin, 'rgflMax:', rgflMax);
});

nodemod.on('engChangeLevel', (s1, s2) => {
  console.log('[engChangeLevel]', 's1:', s1, 's2:', s2);
});

nodemod.on('engGetSpawnParms', (ent) => {
  console.log('[engGetSpawnParms]', 'ent:', ent);
});

nodemod.on('engSaveSpawnParms', (ent) => {
  console.log('[engSaveSpawnParms]', 'ent:', ent);
});

nodemod.on('engVecToYaw', (rgflVector) => {
  console.log('[engVecToYaw]', 'rgflVector:', rgflVector);
});

nodemod.on('engVecToAngles', (rgflVectorIn, rgflVectorOut) => {
  console.log('[engVecToAngles]', 'rgflVectorIn:', rgflVectorIn, 'rgflVectorOut:', rgflVectorOut);
});

nodemod.on('engMoveToOrigin', (ent, pflGoal, dist, iMoveType) => {
  console.log('[engMoveToOrigin]', 'ent:', ent, 'pflGoal:', pflGoal, 'dist:', dist, 'iMoveType:', iMoveType);
});

nodemod.on('engChangeYaw', (ent) => {
  console.log('[engChangeYaw]', 'ent:', ent);
});

nodemod.on('engChangePitch', (ent) => {
  console.log('[engChangePitch]', 'ent:', ent);
});

nodemod.on('engFindEntityByString', (pEdictStartSearchAfter, pszField, pszValue) => {
  console.log('[engFindEntityByString]', 'pEdictStartSearchAfter:', pEdictStartSearchAfter, 'pszField:', pszField, 'pszValue:', pszValue);
});

nodemod.on('engGetEntityIllum', (pEnt) => {
  console.log('[engGetEntityIllum]', 'pEnt:', pEnt);
});

nodemod.on('engFindEntityInSphere', (pEdictStartSearchAfter, org, rad) => {
  console.log('[engFindEntityInSphere]', 'pEdictStartSearchAfter:', pEdictStartSearchAfter, 'org:', org, 'rad:', rad);
});

nodemod.on('engFindClientInPVS', (pEdict) => {
  console.log('[engFindClientInPVS]', 'pEdict:', pEdict);
});

nodemod.on('engEntitiesInPVS', (pplayer) => {
  console.log('[engEntitiesInPVS]', 'pplayer:', pplayer);
});

nodemod.on('engMakeVectors', (rgflVector) => {
  console.log('[engMakeVectors]', 'rgflVector:', rgflVector);
});

nodemod.on('engAngleVectors', (rgflVector, forward, right, up) => {
  console.log('[engAngleVectors]', 'rgflVector:', rgflVector, 'forward:', forward, 'right:', right, 'up:', up);
});

nodemod.on('engCreateEntity', () => {
  console.log('[engCreateEntity]');
});

nodemod.on('engRemoveEntity', (e) => {
  console.log('[engRemoveEntity]', 'e:', e);
});

nodemod.on('engCreateNamedEntity', (className) => {
  console.log('[engCreateNamedEntity]', 'className:', className);
});

nodemod.on('engMakeStatic', (ent) => {
  console.log('[engMakeStatic]', 'ent:', ent);
});

nodemod.on('engEntIsOnFloor', (e) => {
  console.log('[engEntIsOnFloor]', 'e:', e);
});

nodemod.on('engDropToFloor', (e) => {
  console.log('[engDropToFloor]', 'e:', e);
});

nodemod.on('engWalkMove', (ent, yaw, dist, iMode) => {
  console.log('[engWalkMove]', 'ent:', ent, 'yaw:', yaw, 'dist:', dist, 'iMode:', iMode);
});

nodemod.on('engSetOrigin', (e, rgflOrigin) => {
  console.log('[engSetOrigin]', 'e:', e, 'rgflOrigin:', rgflOrigin);
});

nodemod.on('engEmitSound', (entity, channel, sample, volume, attenuation, fFlags, pitch) => {
  console.log('[engEmitSound]', 'entity:', entity, 'channel:', channel, 'sample:', sample, 'volume:', volume, 'attenuation:', attenuation, 'fFlags:', fFlags, 'pitch:', pitch);
});

nodemod.on('engEmitAmbientSound', (entity, pos, samp, vol, attenuation, fFlags, pitch) => {
  console.log('[engEmitAmbientSound]', 'entity:', entity, 'pos:', pos, 'samp:', samp, 'vol:', vol, 'attenuation:', attenuation, 'fFlags:', fFlags, 'pitch:', pitch);
});

nodemod.on('engTraceLine', (start, end, flags, skipEntity) => {
  console.log('[engTraceLine]', 'start:', start, 'end:', end, 'flags:', flags, 'skipEntity:', skipEntity);
});

nodemod.on('engTraceToss', (pent, pentToIgnore) => {
  console.log('[engTraceToss]', 'pent:', pent, 'pentToIgnore:', pentToIgnore);
});

nodemod.on('engTraceMonsterHull', (pEdict, v1, v2, fNoMonsters, pentToSkip) => {
  console.log('[engTraceMonsterHull]', 'pEdict:', pEdict, 'v1:', v1, 'v2:', v2, 'fNoMonsters:', fNoMonsters, 'pentToSkip:', pentToSkip);
});

nodemod.on('engTraceHull', (v1, v2, fNoMonsters, hullNumber, pentToSkip) => {
  console.log('[engTraceHull]', 'v1:', v1, 'v2:', v2, 'fNoMonsters:', fNoMonsters, 'hullNumber:', hullNumber, 'pentToSkip:', pentToSkip);
});

nodemod.on('engTraceModel', (v1, v2, hullNumber, pent) => {
  console.log('[engTraceModel]', 'v1:', v1, 'v2:', v2, 'hullNumber:', hullNumber, 'pent:', pent);
});

nodemod.on('engTraceTexture', (pTextureEntity, v1, v2) => {
  console.log('[engTraceTexture]', 'pTextureEntity:', pTextureEntity, 'v1:', v1, 'v2:', v2);
});

nodemod.on('engTraceSphere', (v1, v2, fNoMonsters, radius, pentToSkip) => {
  console.log('[engTraceSphere]', 'v1:', v1, 'v2:', v2, 'fNoMonsters:', fNoMonsters, 'radius:', radius, 'pentToSkip:', pentToSkip);
});

nodemod.on('engGetAimVector', (ent, speed, rgflReturn) => {
  console.log('[engGetAimVector]', 'ent:', ent, 'speed:', speed, 'rgflReturn:', rgflReturn);
});

nodemod.on('engServerCommand', (str) => {
  console.log('[engServerCommand]', 'str:', str);
});

nodemod.on('engServerExecute', () => {
  console.log('[engServerExecute]');
});

nodemod.on('engClientCommand', (entity, commandArgs) => {
  console.log('[engClientCommand]', 'entity:', entity, 'commandArgs:', commandArgs);
});

nodemod.on('engParticleEffect', (org, dir, color, count) => {
  console.log('[engParticleEffect]', 'org:', org, 'dir:', dir, 'color:', color, 'count:', count);
});

nodemod.on('engLightStyle', (style, val) => {
  console.log('[engLightStyle]', 'style:', style, 'val:', val);
});

nodemod.on('engDecalIndex', (name) => {
  console.log('[engDecalIndex]', 'name:', name);
});

nodemod.on('engPointContents', (rgflVector) => {
  console.log('[engPointContents]', 'rgflVector:', rgflVector);
});

nodemod.on('engMessageBegin', (msg_dest, msg_type, pOrigin, ed) => {
  console.log('[engMessageBegin]', 'msg_dest:', msg_dest, 'msg_type:', msg_type, 'pOrigin:', pOrigin, 'ed:', ed);
});

nodemod.on('engMessageEnd', () => {
  console.log('[engMessageEnd]');
});

nodemod.on('engWriteByte', (iValue) => {
  console.log('[engWriteByte]', 'iValue:', iValue);
});

nodemod.on('engWriteChar', (iValue) => {
  console.log('[engWriteChar]', 'iValue:', iValue);
});

nodemod.on('engWriteShort', (iValue) => {
  console.log('[engWriteShort]', 'iValue:', iValue);
});

nodemod.on('engWriteLong', (iValue) => {
  console.log('[engWriteLong]', 'iValue:', iValue);
});

nodemod.on('engWriteAngle', (flValue) => {
  console.log('[engWriteAngle]', 'flValue:', flValue);
});

nodemod.on('engWriteCoord', (flValue) => {
  console.log('[engWriteCoord]', 'flValue:', flValue);
});

nodemod.on('engWriteString', (sz) => {
  console.log('[engWriteString]', 'sz:', sz);
});

nodemod.on('engWriteEntity', (iValue) => {
  console.log('[engWriteEntity]', 'iValue:', iValue);
});

nodemod.on('engCVarRegister', (cvar) => {
  console.log('[engCVarRegister]', 'cvar:', cvar);
});

nodemod.on('engCVarGetFloat', (szVarName) => {
  console.log('[engCVarGetFloat]', 'szVarName:', szVarName);
});

nodemod.on('engCVarGetString', (szVarName) => {
  console.log('[engCVarGetString]', 'szVarName:', szVarName);
});

nodemod.on('engCVarSetFloat', (szVarName, flValue) => {
  console.log('[engCVarSetFloat]', 'szVarName:', szVarName, 'flValue:', flValue);
});

nodemod.on('engCVarSetString', (szVarName, szValue) => {
  console.log('[engCVarSetString]', 'szVarName:', szVarName, 'szValue:', szValue);
});

nodemod.on('engAlertMessage', (atype, szFmt) => {
  console.log('[engAlertMessage]', 'atype:', atype, 'szFmt:', szFmt);
});

nodemod.on('engEngineFprintf', (pfile, szFmt) => {
  console.log('[engEngineFprintf]', 'pfile:', pfile, 'szFmt:', szFmt);
});

nodemod.on('engPvAllocEntPrivateData', (pEdict, cb) => {
  console.log('[engPvAllocEntPrivateData]', 'pEdict:', pEdict, 'cb:', cb);
});

nodemod.on('engPvEntPrivateData', (pEdict) => {
  console.log('[engPvEntPrivateData]', 'pEdict:', pEdict);
});

nodemod.on('engFreeEntPrivateData', (pEdict) => {
  console.log('[engFreeEntPrivateData]', 'pEdict:', pEdict);
});

nodemod.on('engSzFromIndex', (iString) => {
  console.log('[engSzFromIndex]', 'iString:', iString);
});

nodemod.on('engAllocString', (szValue) => {
  console.log('[engAllocString]', 'szValue:', szValue);
});

nodemod.on('engGetVarsOfEnt', (pEdict) => {
  console.log('[engGetVarsOfEnt]', 'pEdict:', pEdict);
});

nodemod.on('engPEntityOfEntOffset', (iEntOffset) => {
  console.log('[engPEntityOfEntOffset]', 'iEntOffset:', iEntOffset);
});

nodemod.on('engEntOffsetOfPEntity', (pEdict) => {
  console.log('[engEntOffsetOfPEntity]', 'pEdict:', pEdict);
});

nodemod.on('engIndexOfEdict', (pEdict) => {
  console.log('[engIndexOfEdict]', 'pEdict:', pEdict);
});

nodemod.on('engPEntityOfEntIndex', (iEntIndex) => {
  console.log('[engPEntityOfEntIndex]', 'iEntIndex:', iEntIndex);
});

nodemod.on('engFindEntityByVars', (pvars) => {
  console.log('[engFindEntityByVars]', 'pvars:', pvars);
});

nodemod.on('engGetModelPtr', (pEdict) => {
  console.log('[engGetModelPtr]', 'pEdict:', pEdict);
});

nodemod.on('engRegUserMsg', (pszName, iSize) => {
  console.log('[engRegUserMsg]', 'pszName:', pszName, 'iSize:', iSize);
});

nodemod.on('engAnimationAutomove', (pEdict, flTime) => {
  console.log('[engAnimationAutomove]', 'pEdict:', pEdict, 'flTime:', flTime);
});

nodemod.on('engGetBonePosition', (pEdict, iBone, rgflOrigin, rgflAngles) => {
  console.log('[engGetBonePosition]', 'pEdict:', pEdict, 'iBone:', iBone, 'rgflOrigin:', rgflOrigin, 'rgflAngles:', rgflAngles);
});

nodemod.on('engFunctionFromName', (pName) => {
  console.log('[engFunctionFromName]', 'pName:', pName);
});

nodemod.on('engNameForFunction', (callback) => {
  console.log('[engNameForFunction]', 'callback:', callback);
});

nodemod.on('engClientPrintf', (pEdict, ptype, szMsg) => {
  console.log('[engClientPrintf]', 'pEdict:', pEdict, 'ptype:', ptype, 'szMsg:', szMsg);
});

nodemod.on('engServerPrint', (szMsg) => {
  console.log('[engServerPrint]', 'szMsg:', szMsg);
});

nodemod.on('engCmdArgs', () => {
  console.log('[engCmdArgs]');
});

nodemod.on('engCmdArgv', (argc) => {
  console.log('[engCmdArgv]', 'argc:', argc);
});

nodemod.on('engCmdArgc', () => {
  console.log('[engCmdArgc]');
});

nodemod.on('engGetAttachment', (pEdict, iAttachment, rgflOrigin, rgflAngles) => {
  console.log('[engGetAttachment]', 'pEdict:', pEdict, 'iAttachment:', iAttachment, 'rgflOrigin:', rgflOrigin, 'rgflAngles:', rgflAngles);
});

nodemod.on('engRandomLong', (lLow, lHigh) => {
  console.log('[engRandomLong]', 'lLow:', lLow, 'lHigh:', lHigh);
});

nodemod.on('engRandomFloat', (flLow, flHigh) => {
  console.log('[engRandomFloat]', 'flLow:', flLow, 'flHigh:', flHigh);
});

nodemod.on('engSetView', (pClient, pViewent) => {
  console.log('[engSetView]', 'pClient:', pClient, 'pViewent:', pViewent);
});

nodemod.on('engTime', () => {
  console.log('[engTime]');
});

nodemod.on('engCrosshairAngle', (pClient, pitch, yaw) => {
  console.log('[engCrosshairAngle]', 'pClient:', pClient, 'pitch:', pitch, 'yaw:', yaw);
});

nodemod.on('engLoadFileForMe', (filename) => {
  console.log('[engLoadFileForMe]', 'filename:', filename);
});

nodemod.on('engFreeFile', (buffer) => {
  console.log('[engFreeFile]', 'buffer:', buffer);
});

nodemod.on('engEndSection', (pszSectionName) => {
  console.log('[engEndSection]', 'pszSectionName:', pszSectionName);
});

nodemod.on('engCompareFileTime', (filename1, filename2, iCompare) => {
  console.log('[engCompareFileTime]', 'filename1:', filename1, 'filename2:', filename2, 'iCompare:', iCompare);
});

nodemod.on('engGetGameDir', (szGetGameDir) => {
  console.log('[engGetGameDir]', 'szGetGameDir:', szGetGameDir);
});

nodemod.on('engCvarRegisterVariable', (variable) => {
  console.log('[engCvarRegisterVariable]', 'variable:', variable);
});

nodemod.on('engFadeClientVolume', (pEdict, fadePercent, fadeOutSeconds, holdTime, fadeInSeconds) => {
  console.log('[engFadeClientVolume]', 'pEdict:', pEdict, 'fadePercent:', fadePercent, 'fadeOutSeconds:', fadeOutSeconds, 'holdTime:', holdTime, 'fadeInSeconds:', fadeInSeconds);
});

nodemod.on('engSetClientMaxspeed', (pEdict, fNewMaxspeed) => {
  console.log('[engSetClientMaxspeed]', 'pEdict:', pEdict, 'fNewMaxspeed:', fNewMaxspeed);
});

nodemod.on('engCreateFakeClient', (netname) => {
  console.log('[engCreateFakeClient]', 'netname:', netname);
});

nodemod.on('engRunPlayerMove', (fakeclient, viewangles, forwardmove, sidemove, upmove, buttons, impulse, msec) => {
  console.log('[engRunPlayerMove]', 'fakeclient:', fakeclient, 'viewangles:', viewangles, 'forwardmove:', forwardmove, 'sidemove:', sidemove, 'upmove:', upmove, 'buttons:', buttons, 'impulse:', impulse, 'msec:', msec);
});

nodemod.on('engNumberOfEntities', () => {
  console.log('[engNumberOfEntities]');
});

nodemod.on('engGetInfoKeyBuffer', (e) => {
  console.log('[engGetInfoKeyBuffer]', 'e:', e);
});

nodemod.on('engInfoKeyValue', (infobuffer, key) => {
  console.log('[engInfoKeyValue]', 'infobuffer:', infobuffer, 'key:', key);
});

nodemod.on('engSetKeyValue', (infobuffer, key, value) => {
  console.log('[engSetKeyValue]', 'infobuffer:', infobuffer, 'key:', key, 'value:', value);
});

nodemod.on('engSetClientKeyValue', (clientIndex, entity, key, value) => {
  console.log('[engSetClientKeyValue]', 'clientIndex:', clientIndex, 'entity:', entity, 'key:', key, 'value:', value);
});

nodemod.on('engIsMapValid', (filename) => {
  console.log('[engIsMapValid]', 'filename:', filename);
});

nodemod.on('engStaticDecal', (origin, decalIndex, entityIndex, modelIndex) => {
  console.log('[engStaticDecal]', 'origin:', origin, 'decalIndex:', decalIndex, 'entityIndex:', entityIndex, 'modelIndex:', modelIndex);
});

nodemod.on('engPrecacheGeneric', (s) => {
  console.log('[engPrecacheGeneric]', 's:', s);
});

nodemod.on('engGetPlayerUserId', (e) => {
  console.log('[engGetPlayerUserId]', 'e:', e);
});

nodemod.on('engBuildSoundMsg', (entity, channel, sample, volume, attenuation, fFlags, pitch, msg_dest, msg_type, pOrigin, ed) => {
  console.log('[engBuildSoundMsg]', 'entity:', entity, 'channel:', channel, 'sample:', sample, 'volume:', volume, 'attenuation:', attenuation, 'fFlags:', fFlags, 'pitch:', pitch, 'msg_dest:', msg_dest, 'msg_type:', msg_type, 'pOrigin:', pOrigin, 'ed:', ed);
});

nodemod.on('engIsDedicatedServer', () => {
  console.log('[engIsDedicatedServer]');
});

nodemod.on('engCVarGetPointer', (szVarName) => {
  console.log('[engCVarGetPointer]', 'szVarName:', szVarName);
});

nodemod.on('engGetPlayerWONId', (e) => {
  console.log('[engGetPlayerWONId]', 'e:', e);
});

nodemod.on('engInfoRemoveKey', (s, key) => {
  console.log('[engInfoRemoveKey]', 's:', s, 'key:', key);
});

nodemod.on('engGetPhysicsKeyValue', (pClient, key) => {
  console.log('[engGetPhysicsKeyValue]', 'pClient:', pClient, 'key:', key);
});

nodemod.on('engSetPhysicsKeyValue', (pClient, key, value) => {
  console.log('[engSetPhysicsKeyValue]', 'pClient:', pClient, 'key:', key, 'value:', value);
});

nodemod.on('engGetPhysicsInfoString', (pClient) => {
  console.log('[engGetPhysicsInfoString]', 'pClient:', pClient);
});

nodemod.on('engPrecacheEvent', (type, psz) => {
  console.log('[engPrecacheEvent]', 'type:', type, 'psz:', psz);
});

nodemod.on('engPlaybackEvent', (flags, pInvoker, eventindex, delay, origin, angles, fparam1, fparam2, iparam1, iparam2, bparam1, bparam2) => {
  console.log('[engPlaybackEvent]', 'flags:', flags, 'pInvoker:', pInvoker, 'eventindex:', eventindex, 'delay:', delay, 'origin:', origin, 'angles:', angles, 'fparam1:', fparam1, 'fparam2:', fparam2, 'iparam1:', iparam1, 'iparam2:', iparam2, 'bparam1:', bparam1, 'bparam2:', bparam2);
});

nodemod.on('engSetFatPVS', (org) => {
  console.log('[engSetFatPVS]', 'org:', org);
});

nodemod.on('engSetFatPAS', (org) => {
  console.log('[engSetFatPAS]', 'org:', org);
});

nodemod.on('engCheckVisibility', (entity, pset) => {
  console.log('[engCheckVisibility]', 'entity:', entity, 'pset:', pset);
});

nodemod.on('engDeltaSetField', (pFields, fieldname) => {
  console.log('[engDeltaSetField]', 'pFields:', pFields, 'fieldname:', fieldname);
});

nodemod.on('engDeltaUnsetField', (pFields, fieldname) => {
  console.log('[engDeltaUnsetField]', 'pFields:', pFields, 'fieldname:', fieldname);
});

nodemod.on('engDeltaAddEncoder', (encoderName, callback) => {
  console.log('[engDeltaAddEncoder]', 'encoderName:', encoderName, 'callback:', callback);
});

nodemod.on('engGetCurrentPlayer', () => {
  console.log('[engGetCurrentPlayer]');
});

nodemod.on('engCanSkipPlayer', (player) => {
  console.log('[engCanSkipPlayer]', 'player:', player);
});

nodemod.on('engDeltaFindField', (pFields, fieldname) => {
  console.log('[engDeltaFindField]', 'pFields:', pFields, 'fieldname:', fieldname);
});

nodemod.on('engDeltaSetFieldByIndex', (pFields, fieldNumber) => {
  console.log('[engDeltaSetFieldByIndex]', 'pFields:', pFields, 'fieldNumber:', fieldNumber);
});

nodemod.on('engDeltaUnsetFieldByIndex', (pFields, fieldNumber) => {
  console.log('[engDeltaUnsetFieldByIndex]', 'pFields:', pFields, 'fieldNumber:', fieldNumber);
});

nodemod.on('engSetGroupMask', (mask, op) => {
  console.log('[engSetGroupMask]', 'mask:', mask, 'op:', op);
});

nodemod.on('engCreateInstancedBaseline', (classname, baseline) => {
  console.log('[engCreateInstancedBaseline]', 'classname:', classname, 'baseline:', baseline);
});

nodemod.on('engCvarDirectSet', (variable, value) => {
  console.log('[engCvarDirectSet]', 'variable:', variable, 'value:', value);
});

nodemod.on('engForceUnmodified', (type, mins, maxs, filename) => {
  console.log('[engForceUnmodified]', 'type:', type, 'mins:', mins, 'maxs:', maxs, 'filename:', filename);
});

nodemod.on('engGetPlayerStats', (pClient, ping, packet_loss) => {
  console.log('[engGetPlayerStats]', 'pClient:', pClient, 'ping:', ping, 'packet_loss:', packet_loss);
});

nodemod.on('engAddServerCommand', (commandName, callback) => {
  console.log('[engAddServerCommand]', 'commandName:', commandName, 'callback:', callback);
});

nodemod.on('engVoiceGetClientListening', (iReceiver, iSender) => {
  console.log('[engVoiceGetClientListening]', 'iReceiver:', iReceiver, 'iSender:', iSender);
});

nodemod.on('engVoiceSetClientListening', (iReceiver, iSender, bListen) => {
  console.log('[engVoiceSetClientListening]', 'iReceiver:', iReceiver, 'iSender:', iSender, 'bListen:', bListen);
});

nodemod.on('engGetPlayerAuthId', (e) => {
  console.log('[engGetPlayerAuthId]', 'e:', e);
});

nodemod.on('engSequenceGet', (fileName, entryName) => {
  console.log('[engSequenceGet]', 'fileName:', fileName, 'entryName:', entryName);
});

nodemod.on('engSequencePickSentence', (groupName, pickMethod, picked) => {
  console.log('[engSequencePickSentence]', 'groupName:', groupName, 'pickMethod:', pickMethod, 'picked:', picked);
});

nodemod.on('engGetFileSize', (filename) => {
  console.log('[engGetFileSize]', 'filename:', filename);
});

nodemod.on('engGetApproxWavePlayLen', (filepath) => {
  console.log('[engGetApproxWavePlayLen]', 'filepath:', filepath);
});

nodemod.on('engIsCareerMatch', () => {
  console.log('[engIsCareerMatch]');
});

nodemod.on('engGetLocalizedStringLength', (label) => {
  console.log('[engGetLocalizedStringLength]', 'label:', label);
});

nodemod.on('engRegisterTutorMessageShown', (mid) => {
  console.log('[engRegisterTutorMessageShown]', 'mid:', mid);
});

nodemod.on('engGetTimesTutorMessageShown', (mid) => {
  console.log('[engGetTimesTutorMessageShown]', 'mid:', mid);
});

nodemod.on('engProcessTutorMessageDecayBuffer', (buffer) => {
  console.log('[engProcessTutorMessageDecayBuffer]', 'buffer:', buffer);
});

nodemod.on('engConstructTutorMessageDecayBuffer', (buffer) => {
  console.log('[engConstructTutorMessageDecayBuffer]', 'buffer:', buffer);
});

nodemod.on('engResetTutorMessageDecayData', () => {
  console.log('[engResetTutorMessageDecayData]');
});

nodemod.on('engQueryClientCvarValue', (player, cvarName) => {
  console.log('[engQueryClientCvarValue]', 'player:', player, 'cvarName:', cvarName);
});

nodemod.on('engQueryClientCvarValue2', (player, cvarName, requestID) => {
  console.log('[engQueryClientCvarValue2]', 'player:', player, 'cvarName:', cvarName, 'requestID:', requestID);
});

nodemod.on('engCheckParm', (parm, ppnext) => {
  console.log('[engCheckParm]', 'parm:', parm, 'ppnext:', ppnext);
});

nodemod.on('engPEntityOfEntIndexAllEntities', (iEntIndex) => {
  console.log('[engPEntityOfEntIndexAllEntities]', 'iEntIndex:', iEntIndex);
});

nodemod.on('postEngPrecacheModel', (s) => {
  console.log('[postEngPrecacheModel]', 's:', s);
});

nodemod.on('postEngPrecacheSound', (s) => {
  console.log('[postEngPrecacheSound]', 's:', s);
});

nodemod.on('postEngSetModel', (e, m) => {
  console.log('[postEngSetModel]', 'e:', e, 'm:', m);
});

nodemod.on('postEngModelIndex', (m) => {
  console.log('[postEngModelIndex]', 'm:', m);
});

nodemod.on('postEngModelFrames', (modelIndex) => {
  console.log('[postEngModelFrames]', 'modelIndex:', modelIndex);
});

nodemod.on('postEngSetSize', (e, rgflMin, rgflMax) => {
  console.log('[postEngSetSize]', 'e:', e, 'rgflMin:', rgflMin, 'rgflMax:', rgflMax);
});

nodemod.on('postEngChangeLevel', (s1, s2) => {
  console.log('[postEngChangeLevel]', 's1:', s1, 's2:', s2);
});

nodemod.on('postEngGetSpawnParms', (ent) => {
  console.log('[postEngGetSpawnParms]', 'ent:', ent);
});

nodemod.on('postEngSaveSpawnParms', (ent) => {
  console.log('[postEngSaveSpawnParms]', 'ent:', ent);
});

nodemod.on('postEngVecToYaw', (rgflVector) => {
  console.log('[postEngVecToYaw]', 'rgflVector:', rgflVector);
});

nodemod.on('postEngVecToAngles', (rgflVectorIn, rgflVectorOut) => {
  console.log('[postEngVecToAngles]', 'rgflVectorIn:', rgflVectorIn, 'rgflVectorOut:', rgflVectorOut);
});

nodemod.on('postEngMoveToOrigin', (ent, pflGoal, dist, iMoveType) => {
  console.log('[postEngMoveToOrigin]', 'ent:', ent, 'pflGoal:', pflGoal, 'dist:', dist, 'iMoveType:', iMoveType);
});

nodemod.on('postEngChangeYaw', (ent) => {
  console.log('[postEngChangeYaw]', 'ent:', ent);
});

nodemod.on('postEngChangePitch', (ent) => {
  console.log('[postEngChangePitch]', 'ent:', ent);
});

nodemod.on('postEngFindEntityByString', (pEdictStartSearchAfter, pszField, pszValue) => {
  console.log('[postEngFindEntityByString]', 'pEdictStartSearchAfter:', pEdictStartSearchAfter, 'pszField:', pszField, 'pszValue:', pszValue);
});

nodemod.on('postEngGetEntityIllum', (pEnt) => {
  console.log('[postEngGetEntityIllum]', 'pEnt:', pEnt);
});

nodemod.on('postEngFindEntityInSphere', (pEdictStartSearchAfter, org, rad) => {
  console.log('[postEngFindEntityInSphere]', 'pEdictStartSearchAfter:', pEdictStartSearchAfter, 'org:', org, 'rad:', rad);
});

nodemod.on('postEngFindClientInPVS', (pEdict) => {
  console.log('[postEngFindClientInPVS]', 'pEdict:', pEdict);
});

nodemod.on('postEngEntitiesInPVS', (pplayer) => {
  console.log('[postEngEntitiesInPVS]', 'pplayer:', pplayer);
});

nodemod.on('postEngMakeVectors', (rgflVector) => {
  console.log('[postEngMakeVectors]', 'rgflVector:', rgflVector);
});

nodemod.on('postEngAngleVectors', (rgflVector, forward, right, up) => {
  console.log('[postEngAngleVectors]', 'rgflVector:', rgflVector, 'forward:', forward, 'right:', right, 'up:', up);
});

nodemod.on('postEngCreateEntity', () => {
  console.log('[postEngCreateEntity]');
});

nodemod.on('postEngRemoveEntity', (e) => {
  console.log('[postEngRemoveEntity]', 'e:', e);
});

nodemod.on('postEngCreateNamedEntity', (className) => {
  console.log('[postEngCreateNamedEntity]', 'className:', className);
});

nodemod.on('postEngMakeStatic', (ent) => {
  console.log('[postEngMakeStatic]', 'ent:', ent);
});

nodemod.on('postEngEntIsOnFloor', (e) => {
  console.log('[postEngEntIsOnFloor]', 'e:', e);
});

nodemod.on('postEngDropToFloor', (e) => {
  console.log('[postEngDropToFloor]', 'e:', e);
});

nodemod.on('postEngWalkMove', (ent, yaw, dist, iMode) => {
  console.log('[postEngWalkMove]', 'ent:', ent, 'yaw:', yaw, 'dist:', dist, 'iMode:', iMode);
});

nodemod.on('postEngSetOrigin', (e, rgflOrigin) => {
  console.log('[postEngSetOrigin]', 'e:', e, 'rgflOrigin:', rgflOrigin);
});

nodemod.on('postEngEmitSound', (entity, channel, sample, volume, attenuation, fFlags, pitch) => {
  console.log('[postEngEmitSound]', 'entity:', entity, 'channel:', channel, 'sample:', sample, 'volume:', volume, 'attenuation:', attenuation, 'fFlags:', fFlags, 'pitch:', pitch);
});

nodemod.on('postEngEmitAmbientSound', (entity, pos, samp, vol, attenuation, fFlags, pitch) => {
  console.log('[postEngEmitAmbientSound]', 'entity:', entity, 'pos:', pos, 'samp:', samp, 'vol:', vol, 'attenuation:', attenuation, 'fFlags:', fFlags, 'pitch:', pitch);
});

nodemod.on('postEngTraceLine', (start, end, flags, skipEntity) => {
  console.log('[postEngTraceLine]', 'start:', start, 'end:', end, 'flags:', flags, 'skipEntity:', skipEntity);
});

nodemod.on('postEngTraceToss', (pent, pentToIgnore) => {
  console.log('[postEngTraceToss]', 'pent:', pent, 'pentToIgnore:', pentToIgnore);
});

nodemod.on('postEngTraceMonsterHull', (pEdict, v1, v2, fNoMonsters, pentToSkip) => {
  console.log('[postEngTraceMonsterHull]', 'pEdict:', pEdict, 'v1:', v1, 'v2:', v2, 'fNoMonsters:', fNoMonsters, 'pentToSkip:', pentToSkip);
});

nodemod.on('postEngTraceHull', (v1, v2, fNoMonsters, hullNumber, pentToSkip) => {
  console.log('[postEngTraceHull]', 'v1:', v1, 'v2:', v2, 'fNoMonsters:', fNoMonsters, 'hullNumber:', hullNumber, 'pentToSkip:', pentToSkip);
});

nodemod.on('postEngTraceModel', (v1, v2, hullNumber, pent) => {
  console.log('[postEngTraceModel]', 'v1:', v1, 'v2:', v2, 'hullNumber:', hullNumber, 'pent:', pent);
});

nodemod.on('postEngTraceTexture', (pTextureEntity, v1, v2) => {
  console.log('[postEngTraceTexture]', 'pTextureEntity:', pTextureEntity, 'v1:', v1, 'v2:', v2);
});

nodemod.on('postEngTraceSphere', (v1, v2, fNoMonsters, radius, pentToSkip) => {
  console.log('[postEngTraceSphere]', 'v1:', v1, 'v2:', v2, 'fNoMonsters:', fNoMonsters, 'radius:', radius, 'pentToSkip:', pentToSkip);
});

nodemod.on('postEngGetAimVector', (ent, speed, rgflReturn) => {
  console.log('[postEngGetAimVector]', 'ent:', ent, 'speed:', speed, 'rgflReturn:', rgflReturn);
});

nodemod.on('postEngServerCommand', (str) => {
  console.log('[postEngServerCommand]', 'str:', str);
});

nodemod.on('postEngServerExecute', () => {
  console.log('[postEngServerExecute]');
});

nodemod.on('postEngClientCommand', (entity, commandArgs) => {
  console.log('[postEngClientCommand]', 'entity:', entity, 'commandArgs:', commandArgs);
});

nodemod.on('postEngParticleEffect', (org, dir, color, count) => {
  console.log('[postEngParticleEffect]', 'org:', org, 'dir:', dir, 'color:', color, 'count:', count);
});

nodemod.on('postEngLightStyle', (style, val) => {
  console.log('[postEngLightStyle]', 'style:', style, 'val:', val);
});

nodemod.on('postEngDecalIndex', (name) => {
  console.log('[postEngDecalIndex]', 'name:', name);
});

nodemod.on('postEngPointContents', (rgflVector) => {
  console.log('[postEngPointContents]', 'rgflVector:', rgflVector);
});

nodemod.on('postEngMessageBegin', (msg_dest, msg_type, pOrigin, ed) => {
  console.log('[postEngMessageBegin]', 'msg_dest:', msg_dest, 'msg_type:', msg_type, 'pOrigin:', pOrigin, 'ed:', ed);
});

nodemod.on('postEngMessageEnd', () => {
  console.log('[postEngMessageEnd]');
});

nodemod.on('postEngWriteByte', (iValue) => {
  console.log('[postEngWriteByte]', 'iValue:', iValue);
});

nodemod.on('postEngWriteChar', (iValue) => {
  console.log('[postEngWriteChar]', 'iValue:', iValue);
});

nodemod.on('postEngWriteShort', (iValue) => {
  console.log('[postEngWriteShort]', 'iValue:', iValue);
});

nodemod.on('postEngWriteLong', (iValue) => {
  console.log('[postEngWriteLong]', 'iValue:', iValue);
});

nodemod.on('postEngWriteAngle', (flValue) => {
  console.log('[postEngWriteAngle]', 'flValue:', flValue);
});

nodemod.on('postEngWriteCoord', (flValue) => {
  console.log('[postEngWriteCoord]', 'flValue:', flValue);
});

nodemod.on('postEngWriteString', (sz) => {
  console.log('[postEngWriteString]', 'sz:', sz);
});

nodemod.on('postEngWriteEntity', (iValue) => {
  console.log('[postEngWriteEntity]', 'iValue:', iValue);
});

nodemod.on('postEngCVarRegister', (cvar) => {
  console.log('[postEngCVarRegister]', 'cvar:', cvar);
});

nodemod.on('postEngCVarGetFloat', (szVarName) => {
  console.log('[postEngCVarGetFloat]', 'szVarName:', szVarName);
});

nodemod.on('postEngCVarGetString', (szVarName) => {
  console.log('[postEngCVarGetString]', 'szVarName:', szVarName);
});

nodemod.on('postEngCVarSetFloat', (szVarName, flValue) => {
  console.log('[postEngCVarSetFloat]', 'szVarName:', szVarName, 'flValue:', flValue);
});

nodemod.on('postEngCVarSetString', (szVarName, szValue) => {
  console.log('[postEngCVarSetString]', 'szVarName:', szVarName, 'szValue:', szValue);
});

nodemod.on('postEngAlertMessage', (atype, szFmt) => {
  console.log('[postEngAlertMessage]', 'atype:', atype, 'szFmt:', szFmt);
});

nodemod.on('postEngEngineFprintf', (pfile, szFmt) => {
  console.log('[postEngEngineFprintf]', 'pfile:', pfile, 'szFmt:', szFmt);
});

nodemod.on('postEngPvAllocEntPrivateData', (pEdict, cb) => {
  console.log('[postEngPvAllocEntPrivateData]', 'pEdict:', pEdict, 'cb:', cb);
});

nodemod.on('postEngPvEntPrivateData', (pEdict) => {
  console.log('[postEngPvEntPrivateData]', 'pEdict:', pEdict);
});

nodemod.on('postEngFreeEntPrivateData', (pEdict) => {
  console.log('[postEngFreeEntPrivateData]', 'pEdict:', pEdict);
});

nodemod.on('postEngSzFromIndex', (iString) => {
  console.log('[postEngSzFromIndex]', 'iString:', iString);
});

nodemod.on('postEngAllocString', (szValue) => {
  console.log('[postEngAllocString]', 'szValue:', szValue);
});

nodemod.on('postEngGetVarsOfEnt', (pEdict) => {
  console.log('[postEngGetVarsOfEnt]', 'pEdict:', pEdict);
});

nodemod.on('postEngPEntityOfEntOffset', (iEntOffset) => {
  console.log('[postEngPEntityOfEntOffset]', 'iEntOffset:', iEntOffset);
});

nodemod.on('postEngEntOffsetOfPEntity', (pEdict) => {
  console.log('[postEngEntOffsetOfPEntity]', 'pEdict:', pEdict);
});

nodemod.on('postEngIndexOfEdict', (pEdict) => {
  console.log('[postEngIndexOfEdict]', 'pEdict:', pEdict);
});

nodemod.on('postEngPEntityOfEntIndex', (iEntIndex) => {
  console.log('[postEngPEntityOfEntIndex]', 'iEntIndex:', iEntIndex);
});

nodemod.on('postEngFindEntityByVars', (pvars) => {
  console.log('[postEngFindEntityByVars]', 'pvars:', pvars);
});

nodemod.on('postEngGetModelPtr', (pEdict) => {
  console.log('[postEngGetModelPtr]', 'pEdict:', pEdict);
});

nodemod.on('postEngRegUserMsg', (pszName, iSize) => {
  console.log('[postEngRegUserMsg]', 'pszName:', pszName, 'iSize:', iSize);
});

nodemod.on('postEngAnimationAutomove', (pEdict, flTime) => {
  console.log('[postEngAnimationAutomove]', 'pEdict:', pEdict, 'flTime:', flTime);
});

nodemod.on('postEngGetBonePosition', (pEdict, iBone, rgflOrigin, rgflAngles) => {
  console.log('[postEngGetBonePosition]', 'pEdict:', pEdict, 'iBone:', iBone, 'rgflOrigin:', rgflOrigin, 'rgflAngles:', rgflAngles);
});

nodemod.on('postEngFunctionFromName', (pName) => {
  console.log('[postEngFunctionFromName]', 'pName:', pName);
});

nodemod.on('postEngNameForFunction', (callback) => {
  console.log('[postEngNameForFunction]', 'callback:', callback);
});

nodemod.on('postEngClientPrintf', (pEdict, ptype, szMsg) => {
  console.log('[postEngClientPrintf]', 'pEdict:', pEdict, 'ptype:', ptype, 'szMsg:', szMsg);
});

nodemod.on('postEngServerPrint', (szMsg) => {
  console.log('[postEngServerPrint]', 'szMsg:', szMsg);
});

nodemod.on('postEngCmdArgs', () => {
  console.log('[postEngCmdArgs]');
});

nodemod.on('postEngCmdArgv', (argc) => {
  console.log('[postEngCmdArgv]', 'argc:', argc);
});

nodemod.on('postEngCmdArgc', () => {
  console.log('[postEngCmdArgc]');
});

nodemod.on('postEngGetAttachment', (pEdict, iAttachment, rgflOrigin, rgflAngles) => {
  console.log('[postEngGetAttachment]', 'pEdict:', pEdict, 'iAttachment:', iAttachment, 'rgflOrigin:', rgflOrigin, 'rgflAngles:', rgflAngles);
});

nodemod.on('postEngRandomLong', (lLow, lHigh) => {
  console.log('[postEngRandomLong]', 'lLow:', lLow, 'lHigh:', lHigh);
});

nodemod.on('postEngRandomFloat', (flLow, flHigh) => {
  console.log('[postEngRandomFloat]', 'flLow:', flLow, 'flHigh:', flHigh);
});

nodemod.on('postEngSetView', (pClient, pViewent) => {
  console.log('[postEngSetView]', 'pClient:', pClient, 'pViewent:', pViewent);
});

nodemod.on('postEngTime', () => {
  console.log('[postEngTime]');
});

nodemod.on('postEngCrosshairAngle', (pClient, pitch, yaw) => {
  console.log('[postEngCrosshairAngle]', 'pClient:', pClient, 'pitch:', pitch, 'yaw:', yaw);
});

nodemod.on('postEngLoadFileForMe', (filename) => {
  console.log('[postEngLoadFileForMe]', 'filename:', filename);
});

nodemod.on('postEngFreeFile', (buffer) => {
  console.log('[postEngFreeFile]', 'buffer:', buffer);
});

nodemod.on('postEngEndSection', (pszSectionName) => {
  console.log('[postEngEndSection]', 'pszSectionName:', pszSectionName);
});

nodemod.on('postEngCompareFileTime', (filename1, filename2, iCompare) => {
  console.log('[postEngCompareFileTime]', 'filename1:', filename1, 'filename2:', filename2, 'iCompare:', iCompare);
});

nodemod.on('postEngGetGameDir', (szGetGameDir) => {
  console.log('[postEngGetGameDir]', 'szGetGameDir:', szGetGameDir);
});

nodemod.on('postEngCvarRegisterVariable', (variable) => {
  console.log('[postEngCvarRegisterVariable]', 'variable:', variable);
});

nodemod.on('postEngFadeClientVolume', (pEdict, fadePercent, fadeOutSeconds, holdTime, fadeInSeconds) => {
  console.log('[postEngFadeClientVolume]', 'pEdict:', pEdict, 'fadePercent:', fadePercent, 'fadeOutSeconds:', fadeOutSeconds, 'holdTime:', holdTime, 'fadeInSeconds:', fadeInSeconds);
});

nodemod.on('postEngSetClientMaxspeed', (pEdict, fNewMaxspeed) => {
  console.log('[postEngSetClientMaxspeed]', 'pEdict:', pEdict, 'fNewMaxspeed:', fNewMaxspeed);
});

nodemod.on('postEngCreateFakeClient', (netname) => {
  console.log('[postEngCreateFakeClient]', 'netname:', netname);
});

nodemod.on('postEngRunPlayerMove', (fakeclient, viewangles, forwardmove, sidemove, upmove, buttons, impulse, msec) => {
  console.log('[postEngRunPlayerMove]', 'fakeclient:', fakeclient, 'viewangles:', viewangles, 'forwardmove:', forwardmove, 'sidemove:', sidemove, 'upmove:', upmove, 'buttons:', buttons, 'impulse:', impulse, 'msec:', msec);
});

nodemod.on('postEngNumberOfEntities', () => {
  console.log('[postEngNumberOfEntities]');
});

nodemod.on('postEngGetInfoKeyBuffer', (e) => {
  console.log('[postEngGetInfoKeyBuffer]', 'e:', e);
});

nodemod.on('postEngInfoKeyValue', (infobuffer, key) => {
  console.log('[postEngInfoKeyValue]', 'infobuffer:', infobuffer, 'key:', key);
});

nodemod.on('postEngSetKeyValue', (infobuffer, key, value) => {
  console.log('[postEngSetKeyValue]', 'infobuffer:', infobuffer, 'key:', key, 'value:', value);
});

nodemod.on('postEngSetClientKeyValue', (clientIndex, entity, key, value) => {
  console.log('[postEngSetClientKeyValue]', 'clientIndex:', clientIndex, 'entity:', entity, 'key:', key, 'value:', value);
});

nodemod.on('postEngIsMapValid', (filename) => {
  console.log('[postEngIsMapValid]', 'filename:', filename);
});

nodemod.on('postEngStaticDecal', (origin, decalIndex, entityIndex, modelIndex) => {
  console.log('[postEngStaticDecal]', 'origin:', origin, 'decalIndex:', decalIndex, 'entityIndex:', entityIndex, 'modelIndex:', modelIndex);
});

nodemod.on('postEngPrecacheGeneric', (s) => {
  console.log('[postEngPrecacheGeneric]', 's:', s);
});

nodemod.on('postEngGetPlayerUserId', (e) => {
  console.log('[postEngGetPlayerUserId]', 'e:', e);
});

nodemod.on('postEngBuildSoundMsg', (entity, channel, sample, volume, attenuation, fFlags, pitch, msg_dest, msg_type, pOrigin, ed) => {
  console.log('[postEngBuildSoundMsg]', 'entity:', entity, 'channel:', channel, 'sample:', sample, 'volume:', volume, 'attenuation:', attenuation, 'fFlags:', fFlags, 'pitch:', pitch, 'msg_dest:', msg_dest, 'msg_type:', msg_type, 'pOrigin:', pOrigin, 'ed:', ed);
});

nodemod.on('postEngIsDedicatedServer', () => {
  console.log('[postEngIsDedicatedServer]');
});

nodemod.on('postEngCVarGetPointer', (szVarName) => {
  console.log('[postEngCVarGetPointer]', 'szVarName:', szVarName);
});

nodemod.on('postEngGetPlayerWONId', (e) => {
  console.log('[postEngGetPlayerWONId]', 'e:', e);
});

nodemod.on('postEngInfoRemoveKey', (s, key) => {
  console.log('[postEngInfoRemoveKey]', 's:', s, 'key:', key);
});

nodemod.on('postEngGetPhysicsKeyValue', (pClient, key) => {
  console.log('[postEngGetPhysicsKeyValue]', 'pClient:', pClient, 'key:', key);
});

nodemod.on('postEngSetPhysicsKeyValue', (pClient, key, value) => {
  console.log('[postEngSetPhysicsKeyValue]', 'pClient:', pClient, 'key:', key, 'value:', value);
});

nodemod.on('postEngGetPhysicsInfoString', (pClient) => {
  console.log('[postEngGetPhysicsInfoString]', 'pClient:', pClient);
});

nodemod.on('postEngPrecacheEvent', (type, psz) => {
  console.log('[postEngPrecacheEvent]', 'type:', type, 'psz:', psz);
});

nodemod.on('postEngPlaybackEvent', (flags, pInvoker, eventindex, delay, origin, angles, fparam1, fparam2, iparam1, iparam2, bparam1, bparam2) => {
  console.log('[postEngPlaybackEvent]', 'flags:', flags, 'pInvoker:', pInvoker, 'eventindex:', eventindex, 'delay:', delay, 'origin:', origin, 'angles:', angles, 'fparam1:', fparam1, 'fparam2:', fparam2, 'iparam1:', iparam1, 'iparam2:', iparam2, 'bparam1:', bparam1, 'bparam2:', bparam2);
});

nodemod.on('postEngSetFatPVS', (org) => {
  console.log('[postEngSetFatPVS]', 'org:', org);
});

nodemod.on('postEngSetFatPAS', (org) => {
  console.log('[postEngSetFatPAS]', 'org:', org);
});

nodemod.on('postEngCheckVisibility', (entity, pset) => {
  console.log('[postEngCheckVisibility]', 'entity:', entity, 'pset:', pset);
});

nodemod.on('postEngDeltaSetField', (pFields, fieldname) => {
  console.log('[postEngDeltaSetField]', 'pFields:', pFields, 'fieldname:', fieldname);
});

nodemod.on('postEngDeltaUnsetField', (pFields, fieldname) => {
  console.log('[postEngDeltaUnsetField]', 'pFields:', pFields, 'fieldname:', fieldname);
});

nodemod.on('postEngDeltaAddEncoder', (encoderName, callback) => {
  console.log('[postEngDeltaAddEncoder]', 'encoderName:', encoderName, 'callback:', callback);
});

nodemod.on('postEngGetCurrentPlayer', () => {
  console.log('[postEngGetCurrentPlayer]');
});

nodemod.on('postEngCanSkipPlayer', (player) => {
  console.log('[postEngCanSkipPlayer]', 'player:', player);
});

nodemod.on('postEngDeltaFindField', (pFields, fieldname) => {
  console.log('[postEngDeltaFindField]', 'pFields:', pFields, 'fieldname:', fieldname);
});

nodemod.on('postEngDeltaSetFieldByIndex', (pFields, fieldNumber) => {
  console.log('[postEngDeltaSetFieldByIndex]', 'pFields:', pFields, 'fieldNumber:', fieldNumber);
});

nodemod.on('postEngDeltaUnsetFieldByIndex', (pFields, fieldNumber) => {
  console.log('[postEngDeltaUnsetFieldByIndex]', 'pFields:', pFields, 'fieldNumber:', fieldNumber);
});

nodemod.on('postEngSetGroupMask', (mask, op) => {
  console.log('[postEngSetGroupMask]', 'mask:', mask, 'op:', op);
});

nodemod.on('postEngCreateInstancedBaseline', (classname, baseline) => {
  console.log('[postEngCreateInstancedBaseline]', 'classname:', classname, 'baseline:', baseline);
});

nodemod.on('postEngCvarDirectSet', (variable, value) => {
  console.log('[postEngCvarDirectSet]', 'variable:', variable, 'value:', value);
});

nodemod.on('postEngForceUnmodified', (type, mins, maxs, filename) => {
  console.log('[postEngForceUnmodified]', 'type:', type, 'mins:', mins, 'maxs:', maxs, 'filename:', filename);
});

nodemod.on('postEngGetPlayerStats', (pClient, ping, packet_loss) => {
  console.log('[postEngGetPlayerStats]', 'pClient:', pClient, 'ping:', ping, 'packet_loss:', packet_loss);
});

nodemod.on('postEngAddServerCommand', (commandName, callback) => {
  console.log('[postEngAddServerCommand]', 'commandName:', commandName, 'callback:', callback);
});

nodemod.on('postEngVoiceGetClientListening', (iReceiver, iSender) => {
  console.log('[postEngVoiceGetClientListening]', 'iReceiver:', iReceiver, 'iSender:', iSender);
});

nodemod.on('postEngVoiceSetClientListening', (iReceiver, iSender, bListen) => {
  console.log('[postEngVoiceSetClientListening]', 'iReceiver:', iReceiver, 'iSender:', iSender, 'bListen:', bListen);
});

nodemod.on('postEngGetPlayerAuthId', (e) => {
  console.log('[postEngGetPlayerAuthId]', 'e:', e);
});

nodemod.on('postEngSequenceGet', (fileName, entryName) => {
  console.log('[postEngSequenceGet]', 'fileName:', fileName, 'entryName:', entryName);
});

nodemod.on('postEngSequencePickSentence', (groupName, pickMethod, picked) => {
  console.log('[postEngSequencePickSentence]', 'groupName:', groupName, 'pickMethod:', pickMethod, 'picked:', picked);
});

nodemod.on('postEngGetFileSize', (filename) => {
  console.log('[postEngGetFileSize]', 'filename:', filename);
});

nodemod.on('postEngGetApproxWavePlayLen', (filepath) => {
  console.log('[postEngGetApproxWavePlayLen]', 'filepath:', filepath);
});

nodemod.on('postEngIsCareerMatch', () => {
  console.log('[postEngIsCareerMatch]');
});

nodemod.on('postEngGetLocalizedStringLength', (label) => {
  console.log('[postEngGetLocalizedStringLength]', 'label:', label);
});

nodemod.on('postEngRegisterTutorMessageShown', (mid) => {
  console.log('[postEngRegisterTutorMessageShown]', 'mid:', mid);
});

nodemod.on('postEngGetTimesTutorMessageShown', (mid) => {
  console.log('[postEngGetTimesTutorMessageShown]', 'mid:', mid);
});

nodemod.on('postEngProcessTutorMessageDecayBuffer', (buffer) => {
  console.log('[postEngProcessTutorMessageDecayBuffer]', 'buffer:', buffer);
});

nodemod.on('postEngConstructTutorMessageDecayBuffer', (buffer) => {
  console.log('[postEngConstructTutorMessageDecayBuffer]', 'buffer:', buffer);
});

nodemod.on('postEngResetTutorMessageDecayData', () => {
  console.log('[postEngResetTutorMessageDecayData]');
});

nodemod.on('postEngQueryClientCvarValue', (player, cvarName) => {
  console.log('[postEngQueryClientCvarValue]', 'player:', player, 'cvarName:', cvarName);
});

nodemod.on('postEngQueryClientCvarValue2', (player, cvarName, requestID) => {
  console.log('[postEngQueryClientCvarValue2]', 'player:', player, 'cvarName:', cvarName, 'requestID:', requestID);
});

nodemod.on('postEngCheckParm', (parm, ppnext) => {
  console.log('[postEngCheckParm]', 'parm:', parm, 'ppnext:', ppnext);
});

nodemod.on('postEngPEntityOfEntIndexAllEntities', (iEntIndex) => {
  console.log('[postEngPEntityOfEntIndexAllEntities]', 'iEntIndex:', iEntIndex);
});

console.log('test-all-hooks: Registered 410 event handlers');
